language: python
python:
- '3.6'
cache: pip
branches:
  only:
  - master
install:
- pip install -r requirements.txt
script:
- git clone https://github.com/alexandrevicenzi/Flex.git
- pelican-themes -vi Flex
- make clean
- make html
- python test_blog.py
before_deploy:
- rm -rf content/ Flex/ README.md fabfile.py pelicanconf.py publishconf.py test_blog.py requirements.txt Makefile develop_server.sh
deploy:
  on:
    branch: master
  provider: s3
  bucket: sysengcooking.com
  skip_cleanup: true
  local_dir: ./output
  region: us-east-2
after_deploy:
- aws configure set preview.cloudfront true
- aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"
notifications:
  email:
    on_failure: always
env:
  global:
  - secure: XiR0Efaeu1M9f1Ga8amy6NOaHgDNyaPgkw0vGh+hlJu3gq3NjnY+BmvJtr80GZw7fIsRnA30kCkeux013boWUSrrb1JtfMxBcGU8ZLk5e7p9Kr7GHh/p8Z13xHwt3zgVQX2vNka0InhJxl7rtX0tWPkL+4pl+3sqw2RZ4vwhbC8S4b32GiknqwHHJFjIvF0r5ZpbXWigeAGgSk6pWt3B9eKQ7zX6wx2VhT/oo1EmnWVLYE+Z3inakmJSLlQWJ05/NaCrWojVNeesnzqU/Ti+caWW2T03r9I+/bzcZuQwtrk5rdg/l3WWiaaJcV5an0OxQAbvqL87QuxDeQS/ZudRgZOPstTZt+S1VyxRWgyCn0DSrLpcD26Qs9hBs8JZGAMn+2yXyhtWge3dVfO8Mm7YfmQFr/AATjTO1taRICcpTY22ITSCES8aS1ccB54wHfIXpBgh8xP5v+ahqRcyfStXGdAGaaINUibHThTFebB40oQtDYTfCLUXvP3oUlE8dax4xf9sHN4mpaGne6J3UGqZmA3YPReoOZpGLQXzNYi753nQA9h5qqfaqZPGJqsV28TLYf1KQ81eaDSsnnbtjVrFIe6gRCSe4Q/T6c513LIl9rtgCnOTh7FN8shtjNY09I1zQvZaM78SYeOO698FcMKs4qJ1LSdFsmcZQXbSaWNg2BE=
  - secure: X1iTN+YSfBm+Cvc5l4spFFbroYXybGfZuww/237VHfJBwOaP+1kghQK0Asy9HJ2Dgo2jTGSxSdM1pYTrPo4DA+y7OiLzwegiFSdwJ061d+lKrJyv+nZYhskPhDIypbxOqsoHYDkI9kiYyCq1TlB0aqEZxsyZABf0QfTshd7LeFKLjyNj63FsTney2hr+0hPhraR5Ypxw6Iq7eJsX5wjSTsZnW0C83yOkO20K+QKrF+Z2y59uOtaadHARDhxhFR38keBl+OtMztMtSaCEIoivvTMpcxsnv1/UJJqocUWrym6Q4k1AUMM+Dw7NsPgUTgX49Aqy5MEuncLPBOgeB2Db7tPzFS6mHcvm1sxRrv5UbgJHILwLIUN510Oqgatmz5h+zoC7bb15wxN6mvgNcErWw/NP/ESKyif9PXzkhSs5I/ZOj5zAQ872Do5tPsbkdkMVRhFesAqMmUVVVmgGpYbCI2E+xA5x3WMjHmVHYr7qyUZeXzIzo3JWhHrCDpRv421H4g6HYr7JO4L1Ph/0DWR0d+xpp5tUqW4N9D99XUPliKRWL64OdbZe9kHQcCSawraxVwK2YGEmTTB68KjevQddywcwnkan7cXheseZL6bKrdMtLcDSFfbPcIOxOlkTtGCAoxD+4vyvSLTxdgyYuEPFbXuI8HFxEsZkS2R3R51kmWM=
