language: python
python:
- '3.6'
cache: pip
branches:
  only:
  - master
install:
- pip install -r requirements.txt
script:
- git clone https://github.com/alexandrevicenzi/Flex.git
- pelican-themes -vi Flex
- pelican content
- python test_blog.py
notifications:
  email:
    on_failure: always
deploy:
  provider: s3
  bucket: sysengcooking.com
  endpoint: sysengcooking.com.s3-website.us-east-2.amazonaws.com
  acl: public_read
  region: us-east-2
  on:
    repo: codevbus/blog
  access_key_id:
    secure: WqastfRIFy8clBd1Yo7dLmPGvrmvtdyd/+8Q9JubbYY88XVXEpY3Ly5SjkXO0rbUdN30A70jINGmncZPKBAc1E7xQ4bJtg57cxX5GZnoLk+51+/WAyHwGsZtgaQokUEHYZrzf0tVL7rXPYIDAx46c3dqbtZN96Hqq+UAYd8+9ZtkJEkdkvbC+xRMpUVs/LW80cmmM9hYb5w200Fu9VxUi7rR3Bb5dfcGYPpF30LWZO2YtkXsG9qIXfg1f2PsVXE5rZb9PfGI47lSs5JH+XiiHBocAIuaWZt0drKPQCgUkl6rwgUOwPKxl2DtDnN8gwxMDufdq18HZkce0nrPRbVGMKM8DPgeLsdvx4KJKo79BaKuwQ+Q7Myge1uLJYdARfCXgZRbqzJ0wytXZzaJCFVsXSs1F/h5LgoT0P1gNopvalIwlKTOd+M+28RJSHQcs9DY0netnIZVRStoAGNPjiB1/bmS8fqEYdOO6+OzEdhREbg/63YmD0lCZwzjn7PEZuvTCL/WCNw8Foyrl7Uf6Juso+78wIPwk46HQKSSPeuBK/CDJ6aAGvYerHRyh6OFgUzwcshntZbdTv0p93i9SKIHXH0bw9dSgxFRfZkPtzvA78qpPPdGXIQ6vapLjIsRG2FD6xEcnji9SZLOXCNM0ecYWzRz4HUG4CiBcj2JDkF35qo=
  secret_access_key:
    secure: UHgp1mDm5q2dNzez4VuAOBgjev+kAyMV3oN30BqqWYLkYXqpliD6X/nTBmJOhL1WAMnjZaUss3tEh6JjbBnL24pRPvuJmmcStMBthm+x7N6jeySphtQ9LsV6uklmYWlLP+6TtWYtJLTnZVWAe5yC7JLFot3uaoHObqdjLWa3e++F3MgBHBKHubFhGAqG8oZmydbR/H7SGTE8Y/Q60igSH16pZdtI3+vMQ/kdCm270UmaR3jIdnZypCvLLgWskvkE27KvxP2w3EKZV4gqB2Df8UCPSJOyBVha7weNpRmlcG3qfq7QkU1uvTGm8XTmUHZJBgCdV2+ArqWJlkNzDLKJZppvzwNMnbEcabzuC9xBdnxYQwuGS3/PnoVlgwdKJpRFk2h9GPENpTXTMnAWI/N991FRG46grhlORxsQE2nW4w6JvJA/fJCdWFCk32gg8h56GlHySRbImEa3QX9bOaAjWJJzrp8oSYxcQn0WIFylezLQyrgAqqG0sBymBX8kIJYHoWHchaVtKp37F7JTJhxtWFmSf2LdMpbC87XqoQGe4ceSgvK45PijmUKnl98Mq5QALxZiZqDtyLHeks0RfgbOB9dp1fa0GHyq06npn2fTR7D0fjcMJmtmxjql2jwBLwwDb+BzV5rQJO+9jpBnLjhp0UJvFVMN56HZuPl0fmb32C0=
after_deploy:
- aws configure set preview.cloudfront true
- aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID
