language: python
python:
- '3.6'
cache: pip
branches:
  only:
  - master
install:
- pip install -r requirements.txt
script:
- ls
- git clone https://github.com/alexandrevicenzi/Flex.git
- pelican-themes -vi Flex
- pelican content
- python test_blog.py
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_key_id: $AWS_SECRET_KEY
  bucket: sysengcooking.com
  endpoint: sysengcooking.com.s3-website.us-east-2.amazonaws.com
  region: us-east-2
  skip_cleanup: true
  local-dir: output
  acl: public_read
  detect_encoding: true
after_deploy:
- aws configure set preview.cloudfront true
- aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID
notifications:
  email:
    on_failure: always
