baseurl = "https://sysengcooking.com"
theme = "mainroad"
title = "mike vanbuskirk i/o"
paginate = 5
pygmentsCodeFences = true
pygmentsStyle = "native"
enableEmoji = true
languageCode = "en-us"
googleAnalytics = "UA-112057976-1"
disqusShortname = "sysengcooking"

[Author]
  name = "Mike Vanbuskirk"

[Params]
  subtitle = "musings, tutorials, thoughts, ramblings, and random prose"
  description = "Mike Vanbuskirk's personal blog"
  copyright = "Mike Vanbuskirk"
  toc = true
  post_navigation = true
  post_meta = ["date", "categories"]
  highlightColor = "#0379d3"

[Params.sidebar]
  home = "right"
  list = "right"
  single = false
  widgets = ["search", "recent", "categories", "taglist", "social"]

[Params.widgets]
  recent_num = 5
  tags_counter = false

[Params.widgets.social]
  linkedin = "mikevanbuskirk"
  github = "codevbus"
  twitter = "mikevanbus"