baseurl = "https://sysengcooking.com/"
title = "mike vanbuskirk i/o"
author = "Mike Vanbuskirk"
paginate = 4
theme = "arabica"
PygmentsCodeFences = true
PygmentsStyle = "monokai"

[params]
  linkedin = "mikevanbuskirk"
  github = "codevbus"