site_url: http://127.0.0.1
site_name: Mike Vanbuskirk
copyright: Mike Vanbuskirk
nav:
  - Home: index.md 
  - Blog: posts/index.md
  - About: about.md
  - Projects: projects.md
  - Publications: publications.md
theme:
  name: terminal
  favicon: /img/favicon.ico
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: false
plugins:
  - blogging:
      time_format: "%Y-%m-%d"
      dirs:
        - posts

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.10.0/highlight.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.10.0/languages/bash.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.10.0/languages/python.min.js
  - /overrides/highlight.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.10.0/styles/tokyo-night-dark.min.css
  - /overrides/extra.css
