name: auto-build

on:
  schedule:
    - cron: '0 5 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Trigger Netlify build
      run: curl -X POST -d '{}' https://api.netlify.com/build_hooks/${{ secrets.NETLIFY_HOOK }}
